server:
  port: 8082
  servlet:
    context-path: /web_api
#自定义值
myValue1: xixibaba
myValue2: tiehanhan
#引用自定义值
content: "v1: ${myValue1}, v2: ${myValue2}"
#配置写到类里
redis-host: 192.168.1.57
redis-port: 6379
redis-expire-time: 1800
#日志等级
logging:
  level:
    root: INFO
  path: D:\logs
#数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/power_manager?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true