server:
  port: 8081
  servlet:
    context-path: /web_api
#redis配置
redis-host: 116.62.38.203
redis-port: 6379
redis-expire-time: 1800
#日志等级
logging:
  level:
    root: INFO
  path: /var/log/web_api
#数据源
spring:
  datasource:
    first:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/power_manager?useSSL=false
      username: root
      password: root123456
    second:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/power_manager_user?useSSL=false
      username: root
      password: root123456
    initialSize: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    minIdle: 3
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    filters: stat,wall,slf4j
    slowSqlMillis: 5000
    logSlowSql: true
    mergeSql: true